### ISSUE TITLE
Homepage title

### ISSUE THREAD

**Issue by ethanlennox** [ARazak200/ARazak200.github.io#3]
As a suggestion.  The "Aadam" title on the home page could be implemented in code instead of loading an image.  This would improve responsiveness on mobile platforms as the text will scale and also means that you could implement revolving background images.

To center an element both horizontally and vertically, you can use this CSS class:
```css
.center {
    top: 50%;
    left: 50%;
    position: fixed;  // or "absolute"
    transform: translateX(-50%) translateY(-50%);
}
```
The last transform line is used to move the element 50% left and up based on its size, this means that it will center it perfectly with no issues.  You could also use flexbox, but I think this solution is more elegant.
